name: Create Release
on:
  push:
    tags:
      - 'v*.*.*'
      - '!v*-dev*'
jobs:
  release:
    uses: edgexfoundry/edgex-global-pipelines/.github/workflows/release.yml@release-action
    permissions:
      contents: write